use std::{env, fs, path::Path};

fn main() {
    println!("cargo:rerun-if-changed=assets/icons");

    let root = Path::new("assets/icons");
    let mut entries: Vec<String> = Vec::new();
    let mut stack = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let Ok(read) = fs::read_dir(&dir) else { continue };
        for e in read.flatten() {
            let p = e.path();
            if p.is_dir() {
                stack.push(p);
            } else if p.extension().is_some_and(|x| x == "svg") {
                let rel = p
                    .strip_prefix(root)
                    .unwrap()
                    .to_string_lossy()
                    .replace('\\', "/");
                entries.push(format!(
                    "    (\"{rel}\", include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/assets/icons/{rel}\"))),\n"
                ));
            }
        }
    }
    entries.sort();

    let mut out = String::from("// @generated by build.rs from assets/icons — do not edit.\n");
    out.push_str("pub static CAD_ICONS: &[(&str, &[u8])] = &[\n");
    for e in &entries {
        out.push_str(e);
    }
    out.push_str("];\n");

    let out_dir = env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("cad_icons.rs"), out).unwrap();
}
